# Generated by Django 3.2.8 on 2021-12-21 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceuil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi_annonce', models.CharField(max_length=25)),
                ('prix_annonce', models.PositiveIntegerField()),
                ('numero_vendeur', models.IntegerField()),
                ('lieu_produit', models.CharField(max_length=45)),
                ('email_vendeur', models.EmailField(max_length=50)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.clients')),
            ],
        ),
    ]
