# Generated by Django 3.2.8 on 2022-01-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_annonces_img_annonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='nature',
            field=models.CharField(default='augasion', max_length=50),
        ),
    ]
