# Generated by Django 3.2.8 on 2022-01-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0003_annonces_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='A_type',
            field=models.CharField(default='autre', max_length=50),
        ),
    ]
