# Generated by Django 4.0 on 2022-01-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0006_freelnces'),
    ]

    operations = [
        migrations.DeleteModel(
            name='freelnces',
        ),
    ]
