# Generated by Django 4.0 on 2022-01-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0007_delete_freelnces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='A_type',
            field=models.CharField(choices=[('vetement', 'vetement'), ('chaussure', 'chaussure'), ('chemise', 'chemise'), ('technologie', 'technologie'), ('telephone', 'telephone'), ('ordinateur', 'ordinateur'), ('autre', 'autre')], default='autre', max_length=50),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='desc_annonce',
            field=models.TextField(default='pas de description', verbose_name="description de l'annonce"),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='desi_annonce',
            field=models.CharField(max_length=25, verbose_name="designation d'annonce"),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='img_annonce',
            field=models.ImageField(default='img', upload_to='media/annonces', verbose_name="image d'annonce"),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='nature',
            field=models.CharField(choices=[('augasion', 'augasion'), ('nouveau', 'nouveau')], default='augasion', max_length=50),
        ),
    ]
