# Generated by Django 4.0 on 2022-01-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0008_alter_annonces_a_type_alter_annonces_desc_annonce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='img_annonce',
            field=models.ImageField(upload_to='media/annonces', verbose_name="image d'annonce"),
        ),
    ]
