# Generated by Django 3.2.8 on 2021-12-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomclient', models.CharField(max_length=25)),
                ('prenomclient', models.CharField(max_length=25)),
                ('emailclient', models.EmailField(max_length=45, unique=True)),
                ('nomutilisateur', models.CharField(max_length=25, unique=True)),
                ('motdepasse', models.CharField(max_length=8)),
                ('motdepasse_conf', models.CharField(max_length=8)),
            ],
        ),
    ]
