# Generated by Django 3.2.8 on 2022-01-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='profil',
            field=models.ImageField(default='img', upload_to='media/profil'),
        ),
    ]
