# Generated by Django 3.2.8 on 2022-01-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0002_clients_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='numero',
            field=models.CharField(default='12345', max_length=50),
        ),
    ]
