# Generated by Django 4.0 on 2022-01-18 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0004_freelances'),
    ]

    operations = [
        migrations.CreateModel(
            name='concepts_freelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_concept', models.ImageField(upload_to='media')),
                ('description_concept', models.TextField()),
                ('nomfreelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.clients')),
            ],
        ),
    ]
