# Generated by Django 4.0 on 2022-01-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0005_concepts_freelance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepts_freelance',
            name='nomfreelance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.clients', unique=True),
        ),
    ]
