# Generated by Django 4.0 on 2022-01-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0008_concepts_freelance_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='emailclient',
            field=models.EmailField(max_length=45, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='motdepasse',
            field=models.CharField(max_length=8, verbose_name='mot de passe'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='motdepasse_conf',
            field=models.CharField(max_length=8, verbose_name='confirmation mot de passe'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='nomclient',
            field=models.CharField(max_length=25, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='nomutilisateur',
            field=models.CharField(max_length=25, unique=True, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='clients',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clients',
            name='prenomclient',
            field=models.CharField(max_length=25, verbose_name='Prenom'),
        ),
    ]
