# Generated by Django 4.0 on 2022-01-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0009_alter_clients_emailclient_alter_clients_motdepasse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='numero',
            field=models.IntegerField(verbose_name='numero telephone'),
        ),
        migrations.AlterField(
            model_name='freelances',
            name='qualite',
            field=models.CharField(max_length=200, verbose_name='comp'),
        ),
    ]
