# Generated by Django 4.0 on 2022-02-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0010_alter_clients_numero_alter_freelances_qualite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='emailclient',
            field=models.EmailField(error_messages={'unique': 'email existe dejà'}, max_length=45, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='nomutilisateur',
            field=models.CharField(error_messages={'unique': 'cet nom utilisateur est dejà pris'}, max_length=25, unique=True, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='clients',
            name='profil',
            field=models.ImageField(default='img', error_messages={'non': 'donnez une photo de profile'}, upload_to='media/profil'),
        ),
    ]
