# Generated by Django 4.0 on 2022-03-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0011_alter_clients_emailclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='commenteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posteur', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
