# Generated by Django 3.2.8 on 2021-12-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='media')),
                ('prix', models.PositiveIntegerField()),
                ('quantité', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='articles',
        ),
    ]
