# Generated by Django 3.2.8 on 2021-12-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_auto_20211221_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Type',
            field=models.CharField(default='article', max_length=65),
        ),
    ]
