# Generated by Django 4.0 on 2022-01-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0010_alter_clients_numero_alter_freelances_qualite'),
        ('boutique', '0003_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='commandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomproduitcommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.article', verbose_name='le produit commander')),
                ('nomusercommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.clients', verbose_name='le commandeur')),
            ],
        ),
    ]
