# Generated by Django 4.0 on 2022-01-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0011_alter_clients_emailclient_and_more'),
        ('boutique', '0005_commandes_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes_all',
            name='nomproduitcommande_all',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.commandes'),
        ),
        migrations.AlterField(
            model_name='commandes_all',
            name='nomusercommande_all',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.clients'),
        ),
    ]
