# Generated by Django 4.0 on 2022-01-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0011_alter_clients_emailclient_and_more'),
        ('boutique', '0006_alter_commandes_all_nomproduitcommande_all_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='commandes_alls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomproduitcommande_all', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
                ('nomusercommande_all', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.clients')),
            ],
        ),
        migrations.DeleteModel(
            name='commandes_all',
        ),
    ]
