# Generated by Django 4.0 on 2022-03-10 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_commandes_alls_delete_commandes_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes_alls',
            name='date_commande',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
